#!/usr/bin/env tsx

/**
 * Generates a flattened dprint.jsonc from modular configs.
 *
 * Reads from:
 *   - dprint.jsonc (root config)
 *   - config/overrides/*.jsonc (plugin configs)
 *
 * Outputs to:
 *   - internal/generated/dprint-home.jsonc
 *
 * This is a pure generation function - it does not install anywhere.
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { getAllConfigPaths, getOrderedPluginKeys, PLUGINS } from 'config/plugins.registry';

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = path.resolve(SCRIPT_DIR, '..');

const OUTPUT_DIR = path.join(PACKAGE_ROOT, 'internal', 'generated');
const OUTPUT_FILE = 'dprint-home.jsonc';

/**
 * Clean JSONC for JSON.parse: strips comments and trailing commas.
 * Source files keep their comments—this only cleans for parsing.
 */
function cleanJsonc(text: string): string {
  let result = '';
  let i = 0;
  let inString = false;

  while (i < text.length) {
    const char = text[i];
    const next = text[i + 1];

    // Track string state to avoid stripping inside strings
    if (!inString && char === '"') {
      inString = true;
      result += char;
      i++;
      continue;
    }

    if (inString) {
      result += char;
      if (char === '"' && text[i - 1] !== '\\') {
        inString = false;
      }
      i++;
      continue;
    }

    // Line comment (//)
    if (char === '/' && next === '/') {
      while (i < text.length && text[i] !== '\n') i++;
      continue;
    }

    // Block comment (/* */)
    if (char === '/' && next === '*') {
      i += 2;
      while (i < text.length && !(text[i] === '*' && text[i + 1] === '/')) i++;
      i += 2;
      continue;
    }

    result += char;
    i++;
  }

  // Remove trailing commas before ] or }
  return result.replace(/,(\s*[}\]])/g, '$1');
}

/**
 * Parse JSONC content (handles comments + trailing commas).
 */
function parseJsonc(text: string): Record<string, unknown> {
  return JSON.parse(cleanJsonc(text)) as Record<string, unknown>;
}

async function readConfig(relativePath: string): Promise<Record<string, unknown>> {
  const fullPath = path.join(PACKAGE_ROOT, relativePath);
  const content = await fs.readFile(fullPath, 'utf8');
  return parseJsonc(content);
}

/**
 * Generates a flattened dprint.jsonc from modular configs.
 *
 * @returns The path to the generated file
 */
export async function generateFlatConfig(): Promise<string> {
  const rootConfig = await readConfig('dprint.jsonc');

  const plugins: string[] = [];
  const pluginSettings: Record<string, unknown> = {};

  const configPaths = getAllConfigPaths();

  for (const configPath of configPaths) {
    const config = await readConfig(configPath);

    if (Array.isArray(config.plugins)) {
      plugins.push(...(config.plugins as string[]));
    }

    // Extract plugin-specific settings (everything except $schema and plugins)
    // Skip empty objects (they cause dprint config errors)
    for (const [key, value] of Object.entries(config)) {
      if (key === '$schema' || key === 'plugins') continue;
      if (typeof value === 'object' && value !== null && Object.keys(value).length === 0) continue;
      pluginSettings[key] = value;
    }
  }

  // Build the flattened config
  const flatConfig: Record<string, unknown> = {
    $schema: 'https://dprint.dev/schemas/v0.json',

    // Global settings from root
    lineWidth: rootConfig.lineWidth,
    indentWidth: rootConfig.indentWidth,
    useTabs: rootConfig.useTabs,
    newLineKind: rootConfig.newLineKind,

    // Excludes (adjust for home use - more permissive)
    excludes: [
      '**/node_modules',
      '**/*-lock.json',
      '**/*-lock.yaml',
      '**/dist',
      '**/build',
      '**/.git',
    ],

    ...pluginSettings,

    plugins,
  };

  // Generate JSONC output with section comments
  const header = `// Generated by @finografic/dprint-config
// This is a flattened config for use as ~/dprint.jsonc (global fallback)
`;

  const jsonOutput = JSON.stringify(flatConfig, null, 2);

  // Build section comment replacements from plugin config
  let withComments = jsonOutput.replace(
    /^(\s*)"excludes":/m,
    '$1// Global excludes\n$1"excludes":',
  );

  // Add plugin section comments based on centralized config
  const pluginKeys = getOrderedPluginKeys();
  for (const key of pluginKeys) {
    const plugin = PLUGINS[key];
    const regex = new RegExp(`^(\\s*)"${plugin.configKey}":`, 'm');
    withComments = withComments.replace(
      regex,
      `\n$1// ─── ${plugin.displayName} Plugin ───\n$1"${plugin.configKey}":`,
    );
  }

  withComments = withComments.replace(
    /^(\s*)"plugins":/m,
    '\n$1// ─── Plugin URLs ───\n$1"plugins":',
  );

  const output = header + withComments + '\n';

  // Ensure output directory exists
  await fs.mkdir(OUTPUT_DIR, { recursive: true });

  const outputPath = path.join(OUTPUT_DIR, OUTPUT_FILE);
  await fs.writeFile(outputPath, output, 'utf8');

  return outputPath;
}
