#!/usr/bin/env tsx

/**
 * NOTE: Generates a flattened dprint.jsonc for use as a global config in user home folder.
 *
 * Usage:
 *   pnpm home.config.generate          # outputs to generated/dprint-home.jsonc
 *   pnpm home.config.install           # copies to ~/dprint.jsonc
 */

import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = path.resolve(SCRIPT_DIR, '..');

const OUTPUT_DIR = path.join(PACKAGE_ROOT, 'generated');
const OUTPUT_FILE = 'dprint-home.jsonc';
const HOME_TARGET = path.join(os.homedir(), 'dprint.jsonc');

// Config files to merge (order matters for override precedence)
const CONFIG_FILES = [
  'configs/dprint-json.jsonc',
  'configs/dprint-typescript.jsonc',
  'configs/dprint-markdown.jsonc',
  'configs/dprint-toml.jsonc',
  'configs/dprint-yaml.jsonc',
  'configs/dprint-malva.jsonc',
  'configs/dprint-markup.jsonc',
];

/**
 * Strip JSONC comments (// and /* *\/) for JSON.parse compatibility.
 */
function stripJsoncComments(text: string): string {
  let result = '';
  let i = 0;
  let inString = false;
  let stringChar = '';

  while (i < text.length) {
    const char = text[i];
    const next = text[i + 1];

    // Track string state to avoid stripping inside strings
    if (!inString && (char === '"' || char === "'")) {
      inString = true;
      stringChar = char;
      result += char;
      i++;
      continue;
    }

    if (inString) {
      result += char;
      if (char === stringChar && text[i - 1] !== '\\') {
        inString = false;
      }
      i++;
      continue;
    }

    // Line comment
    if (char === '/' && next === '/') {
      while (i < text.length && text[i] !== '\n') i++;
      continue;
    }

    // Block comment
    if (char === '/' && next === '*') {
      i += 2;
      while (i < text.length && !(text[i] === '*' && text[i + 1] === '/')) i++;
      i += 2;
      continue;
    }

    result += char;
    i++;
  }

  return result;
}

/**
 * Parse JSONC content, stripping comments first.
 */
function parseJsonc(text: string): Record<string, unknown> {
  const stripped = stripJsoncComments(text);
  // Also handle trailing commas (common in JSONC)
  const fixed = stripped.replace(/,(\s*[}\]])/g, '$1');
  return JSON.parse(fixed) as Record<string, unknown>;
}

async function readConfig(relativePath: string): Promise<Record<string, unknown>> {
  const fullPath = path.join(PACKAGE_ROOT, relativePath);
  const content = await fs.readFile(fullPath, 'utf8');
  return parseJsonc(content);
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const shouldInstall = args.includes('--install');

  // Read root config for global settings
  const rootConfig = await readConfig('dprint.jsonc');

  // Collect all plugin configs
  const plugins: string[] = [];
  const pluginSettings: Record<string, unknown> = {};

  for (const configPath of CONFIG_FILES) {
    const config = await readConfig(configPath);

    // Extract plugins array
    if (Array.isArray(config.plugins)) {
      plugins.push(...(config.plugins as string[]));
    }

    // Extract plugin-specific settings (everything except $schema and plugins)
    // Skip empty objects (they cause dprint config errors)
    for (const [key, value] of Object.entries(config)) {
      if (key === '$schema' || key === 'plugins') continue;
      if (typeof value === 'object' && value !== null && Object.keys(value).length === 0) continue;
      pluginSettings[key] = value;
    }
  }

  // Build the flattened config
  const flatConfig: Record<string, unknown> = {
    $schema: 'https://dprint.dev/schemas/v0.json',

    // Global settings from root
    lineWidth: rootConfig.lineWidth,
    indentWidth: rootConfig.indentWidth,
    useTabs: rootConfig.useTabs,
    newLineKind: rootConfig.newLineKind,

    // Excludes (adjust for home use - more permissive)
    excludes: [
      '**/node_modules',
      '**/*-lock.json',
      '**/*-lock.yaml',
      '**/dist',
      '**/build',
      '**/.git',
    ],

    // All plugin settings merged
    ...pluginSettings,

    // All plugins
    plugins,
  };

  // Generate JSONC output with header comment
  const header = `// Generated by @finografic/dprint-config
// Run: pnpm home.config.generate
// This is a flattened config for use as ~/dprint.jsonc (global fallback)
`;

  const jsonOutput = JSON.stringify(flatConfig, null, 2);
  const output = header + jsonOutput + '\n';

  // Ensure output directory exists
  await fs.mkdir(OUTPUT_DIR, { recursive: true });

  const outputPath = path.join(OUTPUT_DIR, OUTPUT_FILE);
  await fs.writeFile(outputPath, output, 'utf8');
  console.log(`✅ Generated: ${outputPath}`);

  // Optionally install to home
  if (shouldInstall) {
    await fs.copyFile(outputPath, HOME_TARGET);
    console.log(`✅ Installed: ${HOME_TARGET}`);
  } else {
    console.log(`\n💡 To install to home directory, run:`);
    console.log(`   pnpm home.config.install`);
    console.log(`\n   Or manually copy to: ${HOME_TARGET}`);
  }
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
